### ISSUE TITLE
install or use

### ISSUE THREAD

**Issue by ai4hub** [karolzlot/office-keep-last-item#1]
how to use

**Comment by karolzlot** [comment]
1. Install AutoHotkey V2 from https://www.autohotkey.com/
2. Run .ahk file

**Comment by ai4hub** [comment]
thanks but it did not work on win 11. I just switched to libre or something

**Comment by karolzlot** [comment]
this works only with MS Office, also it works on Win 10, I don't know about Win 11

**Comment by ai4hub** [comment]
it has been resolved

**Comment by karolzlot** [comment]
thank you!
